eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-feign
#service-hi
# ribbon:
#   listOfServers:http://localhost:8762,http://localhost:8763